# Move status line to top
set -g status on
set-option -g status-position top

# Remap prefix from 'C-b' to C-z'
unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# Remap split pane 
unbind '"'
unbind %
bind '"' split-window -h
bind - split-window -v

# Set color scheme to 256 - needed for most vim color schemes
set -g default-terminal "screen-256color"
